#! /usr/bin/env python3

import sys, json
from functools import reduce

output_file = sys.argv[1]
myout_file = sys.argv[2]

with open(output_file, "r") as fh:
    output = json.load(fh)

with open(myout_file, "r") as fh:
    myout = json.load(fh)


def clean(lst):
    # Concatenate everything
    def f(trace):
        parts = list(map(lambda x: x[0] + str(x[1]), trace))
        return reduce(lambda a, b: a+b, parts)

    for e in lst:
        e["vulnerability"] = e["vulnerability"].split("_")[0]
        e["sanitized_flows"] = sorted(e["sanitized_flows"], key=f)

    return lst


def same(a, b):
    if len(a) != len(b):
        return False

    for el in a:
        if el not in b:
            return False
        b.remove(el)
    return True


if same(clean(output), clean(myout)):
    exit(0)

exit(1)
